<a href="https://colab.research.google.com/github/RexelJarell/LINEAR_ALGEBRA/blob/main/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Algebra for ECE

## Laboratory 6: Matrix operations

now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations and matrices and even more

# objectives
at the end of this activity you will be able to:

 1. Be familiar with the fundamental matrix operation
 2. apply the operations to solve intermediate equations
 3. apply matrix algebra in engineering solutions
 

# DISCUSSION

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

#Transposition

one of the fundamental operations in matrix algebra is transposition. The transpose of a matrix is done by flipping the values of its elements over diagonals. wuth this, the rows and columns from the original matrix will be switched so for a matrix A its transpose is denoted as $A^T$
so for examples


$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

In [ ]:
A = np.array ([
               [1, 2 , 5],
               [5, -1, 0],
               [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1]
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

# Try to create your own matrix (you can try non squares) to test transposition

In [ ]:
C = np.array([
              [5,6,7,8],
              [9,1,3,4],
              [1,2,3,4],
              [4,3,2,1]
])
C.shape

(4, 4)

In [ ]:
CT1 = np.transpose(C)
CT1

array([[5, 9, 1, 4],
       [6, 1, 2, 3],
       [7, 3, 3, 2],
       [8, 4, 4, 1]])

In [ ]:
np.transpose(C).shape

(4, 4)

In [ ]:
C.T.shape

(4, 4)

# Dot product /  inner product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

# EXAMPLE

In [ ]:
R = np.array([
    [9,8],
    [5,4]
])
E = np.array([
    [3,7],
    [5,9]
])

In [ ]:
np.dot(R,E)

array([[ 67, 135],
       [ 35,  71]])

In [ ]:
R.dot(E)

array([[ 67, 135],
       [ 35,  71]])

In [ ]:
R @ E

array([[ 67, 135],
       [ 35,  71]])

In [ ]:
np.matmul(R,E)

array([[ 67, 135],
       [ 35,  71]])

# RULE 1: the inner dimensions of the matrices in question must be the same

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
              [2,4],
              [5,-2],
              [0,1]
])
B = np.array([
              [1,1],
              [3,3],
              [-1,-1]
])
C = np.array([
              [0,1,1],
              [1,1,2]
        
])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-1, -2, -3]])

In [ ]:
A @B.T

array([[ 6, 18, -6],
       [ 3,  9, -3],
       [ 1,  3, -1]])

In [ ]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
              [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T@X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X@Y.T

array([[13]])

# RULE 2: dot product has special properties

  Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
B = np.array([
              [9,8,7],
              [6,5,4],
              [3,2,1]
])
C = np.array([
              [1,3,5],
              [7,9,2],
              [4,6,8]
        
])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(3, 3)


#first

In [ ]:
A1 = A@B
A2 = B@A


In [ ]:
np.array_equiv(A1, A2)

False

# second

In [ ]:
A3 = A@(B@C)

In [ ]:
A4 = (A@B)@C

In [ ]:
np.array_equiv(A3, A4)

True

#third

In [ ]:
A5 = A@(B+C)

In [ ]:
A6 = (A@B)+(A@C)

In [ ]:
np.array_equiv(A5, A6)

True

#fourth

In [ ]:
A7 = (B+C)@A

In [ ]:
A8 = (B@A)+(C@A)

In [ ]:
np.array_equiv(A7,A8)

True

#FIFTH

In [ ]:
A9 = np.identity(3)

In [ ]:
A10 = A.dot(np.identity(3))

In [ ]:
np.array_equiv(A9,A10)

False

#DETERMINANTS

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
B = np.array([
    [1,5,2],
    [3,-1,-1],
    [0,-2,1]
])
np.linalg.det(B)

-30.000000000000014

#inverse


In [ ]:
M = np.array([
              [1,7],
              [-3,5]
])
np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [6,9,0],
              [4,2,-1],
              [3,6,7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [ ]:
P = np.array([
              [6,9,0],
              [4,2,-1],
              [3,6,7]
])
np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])